@port = {{$dotenv PORT}}
@baseUrl = http://localhost:{{port}}

### Add a plant
POST {{baseUrl}}/api/plants
Content-Type: application/json

{
"imagePath": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Athyrium_filix-femina.jpg/800px-Athyrium_filix-femina.jpg",
"name": "Rose",
"firstMonth": 0,
"lastMonth": 11,
"place": 2,
"note": "The study of ferns and other pteridophytes is called pteridology. A pteridologist is a specialist in the study of pteridophytes in a broader sense that includes the more distantly related lycophytes.",
"active": false
}

### Find a plant
GET {{baseUrl}}/api/plants/Fern
Content-Type: application/json

### Find all plants
GET {{baseUrl}}/api/plants
Content-Type: application/json

### Delete a plant
DELETE  {{baseUrl}}/api/plants/Fern
Content-Type: application/json